apiVersion: v1
kind: ServiceAccount
metadata:
  name: autoscaler-server
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: autoscaler-server
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "namespaces", "endpoints"]
    verbs: ["get", "list", "watch", "create"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["apps"]
    resources: ["deployments/scale"]
    verbs: ["get", "update", "patch"]
  - apiGroups: ["networking.istio.io"]
    resources: ["gateways", "virtualservices", "destinationrules"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["autoscaling"]
    resources: ["horizontalpodautoscalers"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["metrics.k8s.io"]
    resources: ["pods", "nodes"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: autoscaler-server
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: autoscaler-server
subjects:
  - kind: ServiceAccount
    name: autoscaler-server
    namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: autoscaler-server
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autoscaler-server
  template:
    metadata:
      labels:
        app: autoscaler-server
    spec:
      serviceAccountName: autoscaler-server
      containers:
        - name: autoscaler-server
          image: zewang42/autoscaler-server:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: APP_NAMESPACE
              value: "default"
            - name: BOOKINFO_MANIFEST
              value: "/app/manifests/bookinfo.yaml"
            - name: BOOKINFO_GATEWAY_MANIFEST
              value: "/app/manifests/bookinfo-gateway.yaml"
            - name: PROM_URL
              value: "http://prometheus.istio-system.svc.cluster.local:9090/api/v1/query"
---
apiVersion: v1
kind: Service
metadata:
  name: autoscaler-server
  namespace: default
spec:
  selector:
    app: autoscaler-server
  ports:
    - port: 8000
      targetPort: 8080
      protocol: TCP
  type: ClusterIP
