apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ service_account_name }}
  namespace: {{ namespace }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: das-autoscaler-role
  namespace: {{ namespace }}
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]

  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list"]

  - apiGroups: ["apps"]
    resources: ["deployments/scale"]
    verbs: ["get", "patch", "update"]

  - apiGroups: ["metrics.k8s.io"]
    resources: ["pods", "nodes"]
    verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: das-autoscaler-binding
  namespace: {{ namespace }}
subjects:
  - kind: ServiceAccount
    name: {{ service_account_name }}
    namespace: {{ namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: das-autoscaler-role
